"""Who does the SPEC population leave out? Writes reports/m2_excluded.md.

Candidates = players with any league minutes in the 7 leagues the previous season, whose club on 1 Sep is in those
leagues and who have a valuation. The SPEC keeps those with >= 450 minutes AND a revaluation within the year.
Usage: uv run python -m scout.data.excluded
"""
import pandas as pd

from scout.data.raw import read_raw
from scout.data.snapshots import MIN_PREV_MINUTES, build_snapshots
from scout.ml.intervals import age_band
from scout.ml.train import ROOT, md_table

REPORT = ROOT / "reports" / "m2_excluded.md"


def main() -> None:
    raw = read_raw()
    c = build_snapshots(raw, min_prev_minutes=1)
    dob = raw["players"].set_index("player_id").date_of_birth
    c["age_band"] = age_band((c.date - c.player_id.map(dob)).dt.days / 365.25).astype(str)
    c["low_minutes"] = c.prev_league_minutes < MIN_PREV_MINUTES
    c["no_revaluation"] = ~c.low_minutes & c.target.isna()
    c["kept"] = ~c.low_minutes & c.target.notna()

    def summary(by):
        g = c.groupby(by)
        return pd.DataFrame({"candidates": g.size(), "excluded: < 450 min": g.low_minutes.mean(),
                             "excluded: no revaluation": g.no_revaluation.mean(), "kept": g.kept.mean(),
                             "mean target, kept": g.apply(lambda d: d.target[d.kept].mean(), include_groups=False),
                             "mean target, < 450 min (if revalued)": g.apply(lambda d: d.target[d.low_minutes].mean(), include_groups=False)})

    lines = ["# M2: who the population excludes (auto-generated by `python -m scout.data.excluded`)", "",
             f"{len(c):,} candidate snapshots 2013–2024 (any league minutes in the 7 leagues the previous season, club in "
             "those leagues on 1 Sep, valued). Shares are of candidates. The last column shows the value change the "
             "model never learns from: fringe players (< 450 min) who were revalued.", "",
             "## By year", "", md_table(summary("year")), "", "## By age band", "", md_table(summary("age_band")), ""]
    REPORT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {REPORT}")


if __name__ == "__main__":
    main()
