"""M1 data report: club reconstruction, the valuation-club point-in-time check, and snapshot counts
under both target definitions. Writes reports/m1_data.md.

Usage: uv run python -m scout.data.report
"""
from pathlib import Path

import pandas as pd

from scout.data.raw import read_raw
from scout.data.snapshots import CLUB_METHOD, build_snapshots, club_match_rates

REPORT = Path(__file__).resolve().parents[2] / "reports" / "m1_data.md"


def valuation_club_check(raw: dict) -> dict:
    """Does player_valuations.current_club_id change around transfers (point-in-time), or is it constant?"""
    v, t = raw["valuations"].sort_values("date"), raw["transfers"]
    n_clubs = v.groupby("player_id").current_club_id.nunique()
    moved = t.loc[t.from_club_id != t.to_club_id, "player_id"].unique()
    tr = t[(t.from_club_id != t.to_club_id) & t.date.between("2013-01-01", "2024-12-31")].sort_values("date")
    kw = dict(left_on="date", right_on="vdate", by="player_id")
    vv = v.rename(columns={"date": "vdate"})[["player_id", "vdate", "current_club_id"]]
    before = pd.merge_asof(tr, vv, allow_exact_matches=False, direction="backward", **kw)
    after = pd.merge_asof(tr, vv, direction="forward", **kw)
    year = pd.Timedelta(days=365)
    ok = ((before.date - before.vdate) <= year) & ((after.vdate - after.date) <= year)
    b, a = before[ok], after[ok]
    return {
        "players with >1 valuation club (players with a transfer)": (n_clubs[n_clubs.index.isin(moved)] > 1).mean(),
        "transfers checked (2013–2024, valuations within 365 d on both sides)": int(ok.sum()),
        "last valuation before the transfer shows the old club": (b.current_club_id == b.from_club_id).mean(),
        "first valuation after the transfer shows the new club": (a.current_club_id == a.to_club_id).mean(),
        "valuation club changes across the transfer": (a.current_club_id.to_numpy() != b.current_club_id.to_numpy()).mean(),
    }


def main() -> None:
    from scout.ml.train import md_table
    raw = read_raw()
    rates = club_match_rates(raw)
    check = valuation_club_check(raw)
    s = build_snapshots(raw)
    counts = s.groupby("year").agg(population=("player_id", "size"),
                                   usable_asof_target=("target", lambda x: int(x.notna().sum())),
                                   usable_v0_window=("v0_target_ok", lambda x: int(x.sum())))
    counts.loc["total"] = counts.sum()
    lines = [
        "# M1 data report (auto-generated by `python -m scout.data.report`)", "",
        "## Club at the snapshot date", "",
        ("Match rate = share of players whose reconstructed club on 1 September equals the club they played their "
         "next league game for within 60 days (validation only; the features never look after t). Some misses are "
         "real moves made after 1 September, especially in 2020, when the transfer window stayed open until October."), "",
        ("- `transfers`: last transfer on or before t (the SPEC's first choice). Fails early on because the "
         "transfers table is incomplete before about 2021."),
        "- `august_then_transfers`: last league appearance since 1 August, else transfers (the first fallback).",
        (f"- `latest_evidence` (**used**, `{CLUB_METHOD}`): most recent of the last league appearance, last transfer and "
         "the club on the last valuation, all dated on or before t."), "",
        md_table(rates.rename_axis("year")), "",
        "## Is `player_valuations.current_club_id` point-in-time?", "",
        "Yes. It records the club at the valuation date, not the player's current club:", "",
        *[f"- {k}: {v:.1%}" if isinstance(v, float) else f"- {k}: {v:,}" for k, v in check.items()], "",
        "## Usable snapshots under both target definitions", "",
        ("`usable_asof_target`: the SPEC target (latest valuation on or before the next 1 September, with at least "
         "one new valuation in between). `usable_v0_window`: v0's rule (first valuation 335–425 days after t). "
         "Revaluations bunch in particular months, so the fixed v0 window misses most annual snapshots."), "",
        md_table(counts.rename_axis("year")), "",
        f"Target (SPEC definition, all years): mean {s.target.mean():+.3f}, median {s.target.median():+.3f}, "
        f"{(s.target == 0).mean():.1%} exactly unchanged.", "",
    ]
    REPORT.parent.mkdir(exist_ok=True)
    REPORT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {REPORT}")


if __name__ == "__main__":
    main()
