"""The only code path that evaluates the test set (2023-2024 snapshots). Each run is logged in docs/TEST_LOG.md.

Refits every predictor on 2013-2022 (train + validation) with the tree count chosen on validation, then
scores 2023 and 2024. Requires a clean git tree so the logged commit reproduces the result.

Usage: uv run python -m scout.ml.evaluate_test --confirm-test --reason "M1 final"
"""
import argparse
from datetime import datetime, timezone

import pandas as pd

from scout.data.raw import read_raw
from scout.ml.train import (ROOT, TEST_YEARS, TRAIN_YEARS, VAL_YEAR, best_iteration, build_dataset, fit_predictors,
                            git_commit, mae_diff_ci, md_table, metrics)

LOG = ROOT / "docs" / "TEST_LOG.md"
REPORT = ROOT / "reports" / "test_results.md"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--confirm-test", action="store_true", required=True, help="acknowledge that this spends a test run")
    ap.add_argument("--reason", required=True, help="why the test set is being evaluated (logged)")
    ap.add_argument("--allow-dirty", action="store_true", help="run with uncommitted changes (logged as -dirty)")
    args = ap.parse_args()
    commit = git_commit()
    if commit.endswith("-dirty") and not args.allow_dirty:
        raise SystemExit("Commit your changes first, so the logged commit reproduces this result (or pass --allow-dirty).")

    raw = read_raw()
    dev = build_dataset(raw)
    n_trees = best_iteration(dev[dev.year.isin(TRAIN_YEARS)], dev[dev.year == VAL_YEAR])
    pred = fit_predictors(dev, n_trees)  # refit on 2013-2022
    test = build_dataset(raw, years=TEST_YEARS)
    names = [k for k in pred if not k.startswith("_")]

    tables = {}
    for label, part in [("2023–2024", test), *[(str(y), test[test.year == y]) for y in TEST_YEARS]]:
        tables[label] = pd.DataFrame({m: metrics(part.target, pred[m](part)) for m in names}).T.astype({"n": int}).rename_axis("model")
    y = test.target.to_numpy()
    ci = {b: mae_diff_ci(y, pred["LightGBM"](test), pred[b](test)) for b in ["No change", "Linear (ridge)"]}
    overall = tables["2023–2024"]

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [f"# Test results (auto-generated by `python -m scout.ml.evaluate_test`)", "",
             f"{now}, commit `{commit}`. Reason: {args.reason}", "",
             f"All predictors refit on 2013–2022 ({len(dev):,} snapshots); LightGBM trees = {n_trees} (chosen on 2022).", ""]
    for label, t in tables.items():
        lines += [f"## {label}", "", md_table(t), ""]
    lines += ["MAE difference, LightGBM minus baseline (bootstrap 95% CI; negative = LightGBM better):", "",
              *[f"- vs {b}: {m:+.4f} [{lo:+.4f}, {hi:+.4f}]" for b, (m, lo, hi) in ci.items()], ""]
    REPORT.write_text("\n".join(lines), encoding="utf-8")

    if not LOG.exists():
        LOG.write_text("# Test-set log\n\nEvery evaluation of the test set (2023–2024 snapshots) is appended here by "
                       "`scout/ml/evaluate_test.py`. Rule: at most one run per milestone.\n\n"
                       "| Date | Commit | Reason | n | MAE LightGBM | MAE linear | MAE no-change | Direction LightGBM |\n"
                       "|---|---|---|---|---|---|---|---|\n", encoding="utf-8")
    with open(LOG, "a", encoding="utf-8") as f:
        f.write(f"| {now} | `{commit}` | {args.reason} | {len(test):,} | {overall.loc['LightGBM', 'MAE']:.4f} | "
                f"{overall.loc['Linear (ridge)', 'MAE']:.4f} | {overall.loc['No change', 'MAE']:.4f} | "
                f"{overall.loc['LightGBM', 'Direction acc.']:.3f} |\n")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
