"""The only code path that evaluates the test set (2023-2024 snapshots). Each run is logged in docs/TEST_LOG.md.

Point predictions: every predictor is refit on 2013-2022 (train + validation) with the tuned settings from
scout/ml/best_params.json. Intervals: exactly as served, quantile models fit on 2013-2021 and conformally
calibrated on 2022. Requires a clean git tree so the logged commit reproduces the result.

Usage: uv run --env-file .env python -m scout.ml.evaluate_test --confirm-test --reason "M2 final"
"""
import argparse
from datetime import datetime, timezone

import pandas as pd

from scout.data.raw import read_raw
from scout.ml.intervals import age_band, conformal_margin, coverage_table, fit_quantiles, predict_interval, value_band
from scout.ml.model import to_model_input
from scout.ml.train import (ROOT, TEST_YEARS, TRAIN_YEARS, VAL_YEAR, build_dataset, fit_predictors, git_commit,
                            mae_diff_ci, md_table, metrics)

LOG = ROOT / "docs" / "TEST_LOG.md"
REPORT = ROOT / "reports" / "test_results.md"
LOG_HEADER = ("| Date | Commit | Reason | n | MAE LightGBM | MAE linear | MAE no-change | Direction LightGBM | 80% coverage |\n"
              "|---|---|---|---|---|---|---|---|---|\n")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--confirm-test", action="store_true", required=True, help="acknowledge that this spends a test run")
    ap.add_argument("--reason", required=True, help="why the test set is being evaluated (logged)")
    ap.add_argument("--allow-dirty", action="store_true", help="run with uncommitted changes (logged as -dirty)")
    args = ap.parse_args()
    commit = git_commit()
    if commit.endswith("-dirty") and not args.allow_dirty:
        raise SystemExit("Commit your changes first, so the logged commit reproduces this result (or pass --allow-dirty).")

    raw = read_raw()
    dev = build_dataset(raw)
    pred = fit_predictors(dev)  # refit on 2013-2022
    test = build_dataset(raw, years=TEST_YEARS)
    names = [k for k in pred if not k.startswith("_")]

    train, val = dev[dev.year.isin(TRAIN_YEARS)], dev[dev.year == VAL_YEAR]
    q_lo, q_hi = fit_quantiles(train)
    xv = to_model_input(val)
    margin = conformal_margin(val.target.to_numpy(), q_lo.predict(xv), q_hi.predict(xv))
    lo, hi = predict_interval(test, q_lo, q_hi, margin)
    cov = {"year": coverage_table(test, lo, hi, "year"), "overall": coverage_table(test, lo, hi),
           "age band": coverage_table(test.assign(age_band=age_band(test.age).astype(str)), lo, hi, "age_band"),
           "value band": coverage_table(test.assign(value_band=value_band(test.value_now).astype(str)), lo, hi, "value_band")}

    tables = {}
    for label, part in [("2023–2024", test), *[(str(y), test[test.year == y]) for y in TEST_YEARS]]:
        tables[label] = pd.DataFrame({m: metrics(part.target, pred[m](part)) for m in names}).T.astype({"n": int}).rename_axis("model")
    y = test.target.to_numpy()
    ci = {b: mae_diff_ci(y, pred["LightGBM"](test), pred[b](test)) for b in ["No change", "Linear (ridge)"]}
    overall = tables["2023–2024"]
    coverage = float(cov["overall"].coverage.iloc[0])

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = ["# Test results (auto-generated by `python -m scout.ml.evaluate_test`)", "",
             f"{now}, commit `{commit}`. Reason: {args.reason}", "",
             f"Point predictors refit on 2013–2022 ({len(dev):,} snapshots) with `scout/ml/best_params.json`. "
             f"Intervals: quantile models fit on 2013–2021, conformal margin from 2022 ({margin:+.3f}).", ""]
    for label, t in tables.items():
        lines += [f"## {label}", "", md_table(t), ""]
    lines += ["MAE difference, LightGBM minus baseline (bootstrap 95% CI; negative = LightGBM better):", "",
              *[f"- vs {b}: {m:+.4f} [{lo_:+.4f}, {hi_:+.4f}]" for b, (m, lo_, hi_) in ci.items()], "",
              "## 80% interval coverage (SPEC target 75–85%)", ""]
    for label, t in cov.items():
        lines += [f"By {label}:" if label != "overall" else "Overall:", "", md_table(t), ""]
    REPORT.write_text("\n".join(lines), encoding="utf-8")

    if not LOG.exists():
        LOG.write_text("# Test-set log\n\n", encoding="utf-8")
    text = LOG.read_text(encoding="utf-8")
    if "80% coverage" not in text:  # M2 added a coverage column; earlier rows have none
        text = text.replace("| Date | Commit | Reason | n | MAE LightGBM | MAE linear | MAE no-change | Direction LightGBM |\n"
                            "|---|---|---|---|---|---|---|---|\n", LOG_HEADER)
        text = "\n".join(l + " n/a |" if l.startswith("| 20") else l for l in text.split("\n"))
        if LOG_HEADER not in text:
            text += "\n" + LOG_HEADER
        LOG.write_text(text, encoding="utf-8")
    with open(LOG, "a", encoding="utf-8") as f:
        f.write(f"| {now} | `{commit}` | {args.reason} | {len(test):,} | {overall.loc['LightGBM', 'MAE']:.4f} | "
                f"{overall.loc['Linear (ridge)', 'MAE']:.4f} | {overall.loc['No change', 'MAE']:.4f} | "
                f"{overall.loc['LightGBM', 'Direction acc.']:.3f} | {coverage:.3f} |\n")
    print(f"wrote {REPORT}; appended to {LOG}")


if __name__ == "__main__":
    main()
